### * Get a single person

GET http://localhost:3001/api/persons/64108b5513d52248411b874f

### * Get all persons

GET http://localhost:3001/api/persons/

### * Delete a person

DELETE http://localhost:3001/api/persons/4

### * Create a new person

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Timmy Turnip", 
    "number": "561-944-0394"  
}

### * Update a person

PATCH http://localhost:3001/api/persons/6411ee4059f8f149fe7a6c51
Content-Type: application/json

{
    "name": "Tim Turnip",
    "number": "867-5309"
}