### * Get a single person

GET http://localhost:3001/api/persons/64108b5513d52248411b874f

### * Get all persons

GET http://localhost:3001/api/persons/

### * Delete a person

DELETE http://localhost:3001/api/persons/64124b7f11ff0d85bddef7aa

### * Create a new person

POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Barry Isley", 
    "number": "561-944-034"  
}

### * Update a person

PATCH http://localhost:3001/api/persons/64108853b627044f5e25b28a
Content-Type: application/json

{
    "name": "Juney Love",
    "number": "864-000-0000"
}